deployment:
  tasks:
    - set -e
    - export REPO_DIR="$PWD"
    - export DEPLOY_DIR="$HOME/public_html/dev/apps/ballou-dev"

    # (optionnel) pointer Node 20 si dispo
    - if [ -x /opt/cpanel/ea-nodejs20/bin/node ]; then export PATH="/opt/cpanel/ea-nodejs20/bin:$PATH"; fi

    - export NODE_OPTIONS="--max-old-space-size=512"
    - export NEXT_TELEMETRY_DISABLED=1
    - export NEXT_BASE_PATH="/apps/ballou-dev"

    - mkdir -p "$DEPLOY_DIR"

    # Install
    - if [ -f package-lock.json ]; then npm ci --omit=dev; else npm i --omit=dev; fi

    # Build (Next >=14 + output:'export' => génère /out)
    - npm run build

    # Déploiement atomique : on copie dans un dossier temporaire puis on swap
    - export TMP_DIR="$(mktemp -d "$HOME/tmp/ballou-XXXX")"
    - cp -a "$REPO_DIR/out/." "$TMP_DIR/"
    - rm -rf "$DEPLOY_DIR"
    - mv "$TMP_DIR" "$DEPLOY_DIR"

    - echo "✅ Déployé vers $DEPLOY_DIR à $(date)"
